<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <button data-target="nav-collapse" data-toggle="collapse" class="btn btn-navbar" type="button"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      <a class="brand" href="#"><img src="img/favicon.png"><font>magazine publishing</font></a>
      
      <div class="nav-collapse collapse">
      	<ul class="nav" id="menu-layoutit">
          <li class="divider-vertical"></li>
          <li>
            <div class="btn-group">
              <a class="btn btn-primary" href="http://#" target="_blank"><i class="icon-home icon-white"></i><font>Index</font></a>
            </div>
            <div class="btn-group" data-toggle="buttons-radio">
              <button type="button" id="edit" class="btn btn-primary active"><i class="icon-edit icon-white"></i><font>Edit</font></button>
              <button type="button" class="btn btn-primary" id="devpreview"><i class="icon-eye-close icon-white"></i><font>Layout editor files</font></button>
              <button type="button" class="btn btn-primary" id="sourcepreview"><i class="icon-eye-open icon-white"></i><font>Preview</font></button>
            </div>
            <div class="btn-group">
              <button type="button" class="btn btn-primary" data-target="#downloadModal" rel="/build/downloadModal" role="button" data-toggle="modal"><i class="icon-chevron-down icon-white"></i><font>Downloading</font></button>
              <button class="btn btn-primary" href="/shareasoci/index" role="button" data-toggle="modal" data-target="#shareModal"><i class="icon-share icon-white"></i><font>Share</font></button>
			  <button class="btn btn-primary" href="/share/index" role="button" data-toggle="modal" data-target="#saveModal"><i class="icon-share icon-white"></i><font>save template</font></button>
              <button class="btn btn-primary" href="#clear" id="clear"><i class="icon-trash icon-white"></i><font><font>Delete</font></font></button>
            </div>
            <div class="btn-group">
								<button class="btn btn-primary" href="#undo" id="undo"><i class="icon-arrow-left icon-white"></i><font>Undo</font></button>
								<button class="btn btn-primary" href="#redo" id="redo"><i class="icon-arrow-right icon-white"></i><font>Redo</font></button>
			</div>
          </li>
        </ul>
        
      </div>
      <!--/.nav-collapse --> 
    </div>
  </div>
</div>