
<div class="modal hide fade" role="dialog" id="editorModal">
  <div class="modal-header"> <a class="close" data-dismiss="modal"><font><font>×</font></font></a>
    <h3><font><font>Biên tập viên</font></font></h3>
  </div>
  <div class="modal-body">
    <p>
      <textarea id="contenteditor"></textarea>
    </p>
  </div>
  <div class="modal-footer"> <a id="savecontent" class="btn btn-primary" data-dismiss="modal"><font>Lưu lại</font></a> <a class="btn" data-dismiss="modal"><font>Hủy</font></a> </div>
</div>
<div class="modal hide fade" role="dialog" id="downloadModal">
  <div class="modal-header"> <a class="close" data-dismiss="modal"><font><font>×</font></font></a>
    <h3><font><font>Tải về</font></font></h3>
  </div>
  <div class="modal-body">
    <p><font><font>Đã tạo ra một HTML template, bạn có thể lưu lại .</font></font></p>
    <div class="btn-group">
      <button type="button" id="fluidPage" class="active btn btn-info"><i class="icon-fullscreen icon-white"></i><font><font> Chiều rộng thích ứng</font></font></button>
      <button type="button" class="btn btn-info" id="fixedPage"><i class="icon-screenshot icon-white"></i><font><font> Cố định chiều rộng</font></font></button>
    </div>
    <br>
    <br>
    <p>
      <textarea></textarea>
    </p>
  </div>
  <div class="modal-footer">  
	  <a class="btn btn-primary " id="download" onclick = 'downloadLayout()' >Download .zip</a>
	  <a class="btn btn-primary " id="downloadhtml" onclick = 'downloadHtmlLayout()'>Download .html only</a>
	  <a class="btn" data-dismiss="modal">đóng</a> 
  </div>
</div>

<div class="modal hide fade" role="dialog" id="saveModal">
  <div class="modal-header"> <a class="close" data-dismiss="modal">×</a>
    <h3>Lưu Lại</h3>
  </div>
  <div class="modal-body">Lưu Template thành công</div>
  <div class="modal-footer"> <a class="btn" data-dismiss="modal">Đóng</a> </div>
</div>

<div class="modal fade in" id="shareModal" tabindex="-1" role="dialog" aria-labelledby="shareModalLabel" aria-hidden="true" style="display: none;"><div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h4 class="modal-title">Share</h4>
		</div>
		<div class="modal-body">
						<div id="share-not-logged"> 
												<h4 class="col-sm-offset-4">Login</h4>
				<form action="#" method="post" name="boxDownloadLoginForm" id="boxDownloadLoginForm" class="form-horizontal">
				
										<div class="form-group">
						<label class="control-label col-sm-4" for="login_email">Email address</label>
						<div class="controls col-sm-8">
							<input type="text" name="login[email]" class="form-control" id="login_email">							<span id="email-download-error" class="help-inline"></span>
							<span id="login-download-error" class="help-inline"></span>
						</div>
					</div>
				
					<div class="form-group">
						<label class="control-label col-sm-4" for="login_password">Password</label>
						<div class="controls col-sm-8">
							<input type="password" name="login[password]" class="form-control" id="login_password">							<span id="password-download-error" class="help-inline"></span>
						</div>
					</div>
					<div class="form-group">
						<div class="controls col-sm-8 col-sm-offset-4">
						<label class="checkbox">
							<input type="checkbox" name="login[remember_me]" id="login_remember_me"> Remember me</label>
							<a href="/en/login/password-recovery-request">Forgot your password?</a>
						</div>
					</div>
					<div class="form-group">
						<div class="controls col-sm-8 col-sm-offset-4">
						  <button type="button" class="btn btn-primary" id="modal-download-sign-in-button">Sign in</button>
						</div>
					</div>
				
					<div class="form-group">	
						<p><a class="btn btn-medium btn-info btn-block" href="/socialnetworks/authenticateWithSocial/provider/Facebook">Connect with Facebook!</a></p>
						<p><a class="btn btn-medium btn-info btn-block" href="/socialnetworks/authenticateWithSocial/provider/Twitter">Connect with Twitter!</a></p>
						<p><a class="btn btn-medium btn-info btn-block" href="/socialnetworks/authenticateWithSocial/provider/Google">Connect with Google!</a></p>
						<p><a class="btn btn-medium btn-info btn-block" href="/en/register">Register with Email!</a></p>
						<h5 class="text-center">or</h5>
						<p><span class="btn btn-medium btn-primary btn-block" id="continue-share-non-logged">continue non logged</span></p>
					</div>
				</form>
				
			</div>
						
			<div id="share-logged" class="hide">
				<div class="well text-center">
					<h4><a href="http://bit.ly/ODtxyh" target="_blank">http://bit.ly/ODtxyh</a></h4>
				</div>
				<div class="lead">
						<p class="promote">Share Layout!</p>
		<!-- AddThis Button BEGIN -->
		<div class="addthis_toolbox addthis_default_style addthis_32x32_style">
			<a class="addthis_button_twitter" addthis:description="See the layout I've just make in LayoutIt! Follow this url: http://bit.ly/ODtxyh" addthis:title="LayoutIt! - See my Layout! @layoutit" addthis:url="http://bit.ly/ODtxyh"></a>
			<a class="addthis_button_facebook" addthis:description="See the layout I've just make in LayoutIt! Follow this url: http://bit.ly/ODtxyh" addthis:title="LayoutIt! - See my Layout!" addthis:url="http://bit.ly/ODtxyh"></a>
			<a class="addthis_button_email" addthis:description="See the layout I've just make in LayoutIt! Follow this url: http://bit.ly/ODtxyh" addthis:title="LayoutIt! - See my Layout!" addthis:url="http://bit.ly/ODtxyh"></a>
			<a class="addthis_button_google_plusone" addthis:description="See the layout I've just make in LayoutIt! Follow this url: http://bit.ly/ODtxyh" addthis:title="LayoutIt! - See my Layout!" addthis:url="http://bit.ly/ODtxyh"></a>
		</div>
		<!-- AddThis Button END -->
						</div>
			</div>
        </div>
		<div class="modal-footer">
 			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		</div>
	</div><!-- /.modal-content -->

 
<script type="text/javascript">
		$('#modal-sign-in-button').click(function(event){
			$('.help-inline').hide();
			var form = $('#boxLoginForm');
			var ajaxLoginUrl = '/login/ajaxLogin';
			jQuery.ajax({
		         type : "post",
		         dataType : "json",
		         url : ajaxLoginUrl,
		         data : form.serialize(),
		         success: function(response) {
		        	 if(response.success){
		        		 $('#share-not-logged').hide();
		        		 $('#share-logged').removeClass('hide');
			        	 $('#share-logged').show();
		        	 }else {
			        	if(response.errors && response.errors.length > 0){
			        		$.each(response.errors, function(i, item) {
			                    $('#'+item.field+'-error').html(item.error);
			                    $('#'+item.field+'-error').show();
			        		}); 
				        } 
			         }
				},
				error: function(response) {
					
				}
			});
			
			return false;
		});
</script>
</div>