<?php 
	$config = $this->config;
	$status	  = $this->status;
	$message  = null;
	if($status == 1){
		$message = '<div class="ub_message">Dữ liệu đã được cập nhật thành công</div>';
	}elseif($status == "-1"){
		$message = '<div class="ub_message"><span>Config key bị trùng, vui lòng chọn key khác!</span></div>';
	}
	$active = (int)@$config['active'];
?>
<form id="frmUpdate" name="frmUpdate" method="post" action="<?php echo WEB_PATH;?>/administrator/config/update">
<input type="hidden" id="id" name="id" value="<?php echo $this->id;?>">
<input type="hidden" id="do" name="do" value="submit" />
<article class="module width_full">
<header>
  <h3 class="tabs_involved">Thêm mới / Cập nhật loại tin</h3>
	<div class="functionBtnEvent">
		<ul>
		  <li><a href="<?php echo WEB_PATH;?>/administrator/config">Quay lại trang quản lý</a></li>
		</ul>
	</div>
</header>
<div class="module_content">
	<div class="update_box">
		<?php echo $message;?>
		<div class="ub_left fl">Key</div>
		<div class="ub_right fl"><input type="text" id="config_key" name="config_key" value="<?php echo @$config['config_key'];?>" /></div>
		<div class="cb"></div>	
		<div class="ub_left fl">Value</div>
		<div class="ub_right fl"><input type="text" id="config_value" name="config_value" value="<?php echo @$config['config_value'];?>" /></div>
		<div class="cb"></div>		
		<div class="ub_left fl">Description</div>
		<div class="ub_right fl"><textarea type="text" id="description" name="description"><?php echo @$config['description'];?></textarea></div>
		<div class="cb"></div>
		<div class="ub_button_list">
			<div id="cancel" class="ub_button fl">
				<a href="<?php echo WEB_PATH.'/administrator/config';?>">Quay lại</a>
			</div>
			<div onclick="return validateData()" class="ub_button fl">
				Lưu lại
			</div>
			<div class="cb"></div>
		</div>
		<div class="cb"></div>
	</div>
</div>
</article>
<div class="clear"></div>
</form>