<form id="frmList" name="frmList" method="post">
<input type="hidden" id="keywordUrl" value="<?php echo WEB_PATH;?>/administrator/seopage/keyword/" />
<input type="hidden" id="seoPageUrl" value="<?php echo WEB_PATH;?>/administrator/seopage/" />
<input type="hidden" id="setType" />
<article class="module width_full">
<header>
  <h3 class="tabs_involved">Hệ thống tự động xử lý các tác vụ SEO</h3>	
  <div id="loading" class="loading mt10 fr mt10 mr5"></div>
</header>
<div class="module_content">
	<div class="auto_result_box1">
		<span id="cronjobResult"></span>
	</div>
<div class="cb"></div>
</div>

</article>
<div class="clear"></div>
</form>