<head>
  	
    <title>magazine publishing</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <meta content='text/html;charset=utf-8' http-equiv='content-type'>
    <meta content='Flat administration template for Twitter Bootstrap. Twitter Bootstrap 3 template with Ruby on Rails support.' name='description'>
    <link href='<?php echo WEB_PATH;?>/public/assets/images/maybanhang.ico' rel='shortcut icon' type='image/x-icon'>
    <link href='<?php echo WEB_PATH;?>/public/assets/images/meta_icons/apple-touch-icon.png' rel='apple-touch-icon-precomposed'>
    <link href='<?php echo WEB_PATH;?>/public/assets/images/meta_icons/apple-touch-icon-57x57.png' rel='apple-touch-icon-precomposed' sizes='57x57'>
    <link href='<?php echo WEB_PATH;?>/public/assets/images/meta_icons/apple-touch-icon-72x72.png' rel='apple-touch-icon-precomposed' sizes='72x72'>
    <link href='<?php echo WEB_PATH;?>/public/assets/images/meta_icons/apple-touch-icon-114x114.png' rel='apple-touch-icon-precomposed' sizes='114x114'>
    <link href='<?php echo WEB_PATH;?>/public/assets/images/meta_icons/apple-touch-icon-144x144.png' rel='apple-touch-icon-precomposed' sizes='144x144'>
    <!-- / bootstrap [required] -->
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/bootstrap/bootstrap.css" media="all" rel="stylesheet" type="text/css" />
    <!-- / theme file [required] -->
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/light-theme.css" media="all" id="color-settings-body-color" rel="stylesheet" type="text/css" />
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/view-custom.css" rel="stylesheet" type="text/css" />
    
    
     <!-- / START - page related stylesheets [optional] -->
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/plugins/bootstrap_daterangepicker/bootstrap-daterangepicker.css" media="all" rel="stylesheet" type="text/css" />
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/plugins/fullcalendar/fullcalendar.css" media="all" rel="stylesheet" type="text/css" />
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/plugins/common/bootstrap-wysihtml5.css" media="all" rel="stylesheet" type="text/css" />
    <!-- / END - page related stylesheets [optional] -->
   
    <!-- / coloring file [optional] (if you are going to use custom contrast color) -->
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/theme-colors.css" media="all" rel="stylesheet" type="text/css" />
    <!-- / demo file [not required!] -->
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/demo.css" media="all" rel="stylesheet" type="text/css" />
    <!--[if lt IE 9]>
      <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/ie/html5shiv.js" type="text/javascript"></script>
      <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/ie/respond.min.js" type="text/javascript"></script>
    <![endif]-->
    
     <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/jquery/jquery.min.js" type="text/javascript"></script>
     
    	<!-- <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    	 -->
  </head>