<?php 
	$objACL		= new HT_Model_administrator_models_acl();
	$objMenu	= new HT_Model_administrator_models_menu();
	@$auth 		= Zend_Auth::getInstance();
	$user 		= @$auth->getStorage()->read();
	$groupMenu	= $objMenu->getLeftMenu();
?>
<!-- 
<nav id='main-nav' class=''>
-->
<nav id='main-nav' class='main-nav-fixed affix'>
 
        <div class='navigation'>
        
          <ul class='nav nav-stacked'>
          
          
          
          
          <li>
              <a href="#" style="height: 0px;" ></a>
          </li>
            <li class=''>
        
              <a href='<?php echo WEB_PATH;?>/administrator'>
                <i class='icon-dashboard'></i>
                <span><?php echo ucfirst($user->role_name);?> dashboard</span>
              </a>
            </li>
            
            <li class="sidebar-nav">
              <a class="dropdown-collapse" href="#">
	              <i class="icon-male"></i>
	              <span>BBBBBBBBBBBBBBBBB</span>
	              <i class="icon-angle-down angle-down"></i>
              </a>
              <ul class="nav nav-stacked nav-list accordion-group">
              <li class="nav-header ">
              <a href="<?php echo WEB_PATH;?>/administrator/magazinepublishing">
                  <i class="icon-plus icon-white"></i><font>Layout Colum</font>
              </a>
                  <li style="display: list-item;" class="rows" id="estRows">
			            <div class="lyrow ui-draggable"> <a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font><font>Xóa</font></font></a> <span class="drag label"><i class="icon-move"></i><font><font>Kéo</font></font></span>
			              <div class="preview">
			                <input value="12" type="text">
			              </div>
			              <div class="view">
			                <div class="row-fluid clearfix">
			                  <div class="span12 column"></div>
			                </div>
			              </div>
			            </div>
			            <div class="lyrow ui-draggable"> <a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font><font>Xóa</font></font></a> <span class="drag label"><i class="icon-move"></i><font><font>Kéo</font></font></span>
			              <div class="preview">
			                <input value="6 6" type="text">
			              </div>
			              <div class="view">
			                <div class="row-fluid clearfix">
			                  <div class="span6 column"></div>
			                  <div class="span6 column"></div>
			                </div>
			              </div>
			            </div>
			            <div class="lyrow ui-draggable"> <a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font><font>Xóa</font></font></a> <span class="drag label"><i class="icon-move"></i><font><font>kéo</font></font></span>
			              <div class="preview">
			                <input value="8 4" type="text">
			              </div>
			              <div class="view">
			                <div class="row-fluid clearfix">
			                  <div class="span8 column"></div>
			                  <div class="span4 column"></div>
			                </div>
			              </div>
			            </div>
			            <div class="lyrow ui-draggable"> <a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font><font>Xóa</font></font></a> <span class="drag label"><i class="icon-move"></i><font><font>Kéo</font></font></span>
			              <div class="preview">
			                <input value="4 4 4" type="text">
			              </div>
			              <div class="view">
			                <div class="row-fluid clearfix">
			                  <div class="span4 column"></div>
			                  <div class="span4 column"></div>
			                  <div class="span4 column"></div>
			                </div>
			              </div>
			            </div>
			            <div class="lyrow ui-draggable"> <a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font><font>Xóa</font></font></a> <span class="drag label"><i class="icon-move"></i><font><font>Kéo</font></font></span>
			              <div class="preview">
			                <input value="2 6 4" type="text">
			              </div>
			              <div class="view">
			                <div class="row-fluid clearfix">
			                  <div class="span2 column"></div>
			                  <div class="span6 column"></div>
			                  <div class="span4 column"></div>
			                </div>
			              </div>
			            </div>
			          </li>
              </li>  	
              </ul>
            </li>
          
            
            <?php 
	            if(isset($user->role_id) && (int)$user->role_id >0){
	            	$roldId = (int)$user->role_id;
	            	//$roldId = 13;
	            	$actionRight = $objACL->getActionRight($roldId);
	            	$groupMenu	 = $objMenu->buildLeftMenu($groupMenu,$actionRight);
	            	//echo "<pre>";
	            	//print_r($moduleRight);
	            	foreach((array)$groupMenu as $group){
	            		$groupId 		= $group['group_id'];
	            		$groupName 		= $group['group_name'];
	            		$groupURL 		= $group['group_url'];
	            		$menuList 		= $group['menu_list'];
	            		$groupIcon 		= trim($group['group_icon']);
	            		$hasSub			= $group['has_sub'];
	            		if(!$groupIcon) $groupIcon = 'icon-edit';
           		if($hasSub){ 
	       ?>
            
            <li class=''>
              <a class="dropdown-collapse" href="#">
	              <i class='<?php echo $groupIcon;?>'></i>
	              <span><?php echo $groupName;?></span>
	              <i class='icon-angle-down angle-down'></i>
              </a>
              <ul class='nav nav-stacked'>
              <?php 
		  	   		foreach($menuList as $menu){
						$menuName = $menu['menu_name'];
						$menuUrl = $menu['menu_url'];
						$actionId = $menu['action_id'];
						list($info,$menuUrl) = explode('administrator/', $menuUrl);
						$menuUrl 			 = WEB_PATH.'/administrator/'.$menuUrl;
						if(in_array($actionId,$actionRight)){
		  	   				echo "<li class=''>";
		  	   					echo "<a href='".$menuUrl."'>";
		  	   						echo "<i class='icon-caret-right'></i>";
		  	   						echo "<span>".$menuName."</span>";
		  	   					echo "</a>";
		  	   				echo "</li>";
		  	   			}
		  	   		}
		  	   ?>  	
              </ul>
            </li>
            <?php }else{
            	if(strpos($groupURL, 'administrator')=== FALSE){
            		continue;
            	}else{
            		$arr = explode('administrator', $groupURL);
            		$groupURL = WEB_PATH.'/administrator'.$arr[1];
            	}
            ?>
            <li class=''>
              <a  href="<?php echo $groupURL;?>">
	              <i class='<?php echo $groupIcon;?>'></i>
	              <span><?php echo $groupName;?></span>
              </a>
            </li>
            <?php 
            }}}?>
          </ul>
        </div>
      </nav>