<?php 
	$Identity = $this->Identity;

	echo "<br/>";
	
	$status	  = $this->status;
	//echo $status;
	//echo $this->abc;
	$message  = null;
	if($status ==1){
		$message = '<div class="alert alert-success alert-dismissable">
                <a class="close" data-dismiss="aler" href="#">&times;</a>
                
                <strong>Update</strong>
                Thành công !
                
              </div>';
	}elseif($status == "-1"){
		$message = '<div class="ub_message"><span>url key bị trùng, vui lòng chọn key khác!</span></div>';
	}
	$active = (int)@$Identity['active'];
	echo $message;
?>
<div class='row' id='content-wrapper'>
            <div class='col-xs-12'>
              <div class='row'>
                <div class='col-sm-12'>
                  <div class='page-header'>
                    <h1 class='pull-left'>
                      <i class='icon-edit'></i>
                      <span class="page_title">Thêm mới / Cập nhật Identity</span>
                    </h1>
                  </div>
                </div>
              </div>
              <div class='row'>
                <div class='col-sm-12'>
                  <div class='box'>
                    <div class='box-header blue-background'>
                      <div class='title'>
                        <div class='icon-edit'></div>
                        Identity page
                      </div>
                      <div class='actions'>
                        <a class="btn box-remove btn-xs btn-link" href="#"><i class='icon-remove'></i>
                        </a>
                        <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                        </a>
                      </div>
                    </div>
                    <div class='box-content'>
                    
                    
						<form id="frmUpdate" name="frmUpdate" class="form form-horizontal validate-form" method="post" action="<?php echo WEB_PATH;?>/administrator/identity/update" style="margin-bottom: 0;" accept-charset="UTF-8">
						
						
						<input type="hidden" id="id" name="id" value="<?php echo $this->id;?>">
						<input type="hidden" id="do" name="do" value="submit" />
                        <input name="authenticity_token" type="hidden" />
                        
                        
                       <div class='form-group'>
                          <label class='control-label col-sm-3 col-sm-3' for='form_name'>Name</label>
                          <div class='col-sm-4 controls'>
                            <input class='form-control' data-rule-minlength='6' data-rule-required='true' id='form_name' name='form_name' placeholder='Name' type='text' value="<?php echo @$Identity['form_name'];?>"/>
                          </div>
                        </div>
                      
                      
                      <div class='form-group'>
                          <div class='control-label col-sm-3'>
                            <label for='domain'>Domain</label>
                            <small class='help-block'>http://</small>
                          </div>
                          <div class='col-sm-4 controls'>
                            <input class='form-control' data-rule-required='true' data-rule-url='true' id='domain' name='domain' placeholder='domain' type='text' value="<?php echo @$Identity['domain'];?>"/>
                          </div>
                        </div>
                      
                      
                        <div class='form-group'>
                          <label class='control-label col-sm-3 col-sm-3' for='form_url'>Form url</label>
                          <div class='col-sm-4 controls'>
                            <input class='form-control' data-rule-minlength='6' data-rule-required='true' id='form_url' name='form_url' placeholder='form url' type='text' value="<?php echo @$Identity['form_url'];?>" />
                          </div>
                        </div>
                       
                       
                       
                         <div class='form-group'>
                          <label class='control-label col-sm-3 col-sm-3' for='form_format'>Form format</label>
                          <div class='col-sm-4 controls'>
                            <input class='form-control' data-rule-minlength='6' data-rule-required='true' id='form_format' name='form_format' placeholder='form format' type='text' value="<?php echo @$Identity['form_format'];?>" />
                          </div>
                        </div>
                        
                        <div class='form-group'>
                          <label class='control-label col-sm-3 col-sm-3' for='description'>Description</label>
                          <div class='col-sm-4 controls'>
                            <input class='form-control' data-rule-minlength='6' data-rule-required='true' id='description' name='description' placeholder='description' type='text' value="<?php echo @$Identity['description'];?>" />
                          </div>
                        </div>
                      
                      
                      
                      <div class='form-group'>
                        <label class='col-md-3 control-label' for='reg_dttm' placeholder='reg_dttm'>reg_dttm</label>
                        <div class='col-sm-4 controls'>
                        	<input class='form-control' type="date" id="reg_dttm" name="reg_dttm" value="<?php echo @$Identity['reg_dttm'];?>" />
                        </div>
                      </div>
                      
                       <div class='form-group'>
                        <label class='col-md-3 control-label' for='upd_dttm' placeholder='upd_dttm'>upd_dttm</label>
                        <div class='col-sm-4 controls'>
                        	<input class='form-control' type="date" id="upd_dttm" name="upd_dttm" value="<?php echo @$Identity['upd_dttm'];?>" />
                        </div>
                      </div>
                      
                      <div class='form-actions form-actions-padding-sm'>
                        <div class='row'>
                          <div class='col-md-9 col-md-offset-3'>
                            <button class='btn btn-primary' type="submit" >
                              <i class='icon-save'></i>
                              Save
                            </button>
                            <a href="<?php echo WEB_PATH.'/administrator/identity';?>"><div class='btn'>Cancel</div></a>
                          </div>
                        </div>
                      </div>
                      </form>
                      
                      
                      
                      
                    </div>
                  </div>
                </div>
              </div>
            </div>
</div>