<?php 
	$action = $this->action;
	$status	  = $this->status;
	$message  = null;
	if($status == 1){
		$message = '<div class="ub_message">Dữ liệu đã được cập nhật thành công</div>';
	}elseif($status == "-1"){
		$message = '<div class="ub_message"><span>Có lỗi sảy ra trong quá trình cập nhật dữ liệu</span></div>';
	}
?>
<form id="frmUpdate" name="frmUpdate" method="post" action="<?php echo WEB_PATH;?>/administrator/action/update">
<input type="hidden" id="id" name="id" value="<?php echo $this->id;?>">
<input type="hidden" id="do" name="do" value="submit" />
<article class="module width_full">
<header>
  <h3 class="tabs_involved">Cập nhật chức năng</h3>
	<div class="functionBtnEvent">
		<ul>
		  <li><a href="<?php echo WEB_PATH;?>/administrator/action">Quay lại trang quản lý</a></li>
		</ul>
	</div>
</header>
<div class="module_content">
	<div class="update_box">
		<div class="ub_left fl">Tên module</div>
		<div class="ub_right fl"><?php echo $this->module;?></div>
		<div class="cb"></div>
		<div class="ub_left fl">Tên chức năng</div>
		<div class="ub_right fl"><input type="text" id="action_name" name="action_name" value="<?php echo @$action['action_name'];?>" /></div>
		<div class="cb"></div>
		<div class="ub_left fl">Tên chức năng hiển thị</div>
		<div class="ub_right fl"><input type="text" id="action_name_display" name="action_name_display" value="<?php echo @$action['action_name_display'];?>" /></div>
		<div class="cb"></div>
		<div class="ub_left fl">Mô tả về chức năng</div>
		<div class="ub_right fl"><textarea type="text" id="description" name="description"><?php echo @$action['description'];?></textarea></div>
		<div class="cb"></div>
		<div class="ub_button_list">
			<div id="cancel" class="ub_button fl">
				<a href="<?php echo WEB_PATH.'/administrator/action';?>">Quay lại</a>
			</div>
			<div onclick="return validateData()" class="ub_button fl">
				Lưu lại
			</div>
			<div class="cb"></div>
		</div>
		<div class="cb"></div>
		<?php echo $message;?>
	</div>
</div>
</article>
<div class="clear"></div>
</form>